### ISSUE TITLE
Colours Not Rendered Until First Mouse Move Fired

### ISSUE THREAD

**Issue by moebrowne** [joestrong/triangle-background#1]
On first page load all the triangles are rendered black until the first `mousemove` event is fired.
Tested on both Firefox 41.0.1 and Chromium 45.0.2454.101

![screenshot-joe strong - web developer - chromium](https://cloud.githubusercontent.com/assets/8448512/10419443/256d6f2c-7070-11e5-9ee2-cd9237309719.png)

**Comment by joestrong** [comment]
Thanks! I'm happy to accept a pull request if you fancy making the change

**Comment by moebrowne** [comment]
See PR #2

**Comment by joestrong** [comment]
Thanks for the PR, merged.
