### ISSUE TITLE
Weirdness with hover using custom colours

### ISSUE THREAD

**Issue by moebrowne** [joestrong/triangle-background#6]
If you set the colours to certain combinations you get a strange flickering on mouse hover.

I suspect it's something to do with the `Triangle.changeColour` method but I couldn't work out exactly how it works or what in there is causing this behaviour.

You can replicate the behaviour by using:

``` Javascript
    color: [
        '#dddddd',
        '#cccccc',
        '#bbbbbb',
        '#090909'
    ]
    color: [
        '#000000',
        '#FF0000'
    ]
    color: [
        '#000000',
        '#FFFFFF'
    ]
    // This one is the weirdest...
    color: [
        '#FF0000',
        '#00FF00',
        '#0000FF'
    ]
```

**Comment by joestrong** [comment]
This is now fixed in v0.2.1
Fixed here: bdf505d8874e4e9e7085eccbc8710c9288c36ce7
